
@"comment",
@"comment.block",
@"keyword",
@"keyword.type",
@"language.function",
@"constant",
@"string",
@"string.regex",
@"support",
@"meta.important",
@"style.comment",
@"style.property.name",
@"style.value",
@"style.value.string",
@"style.value.color.rgb-value",
@"style.at-rule",
@"markup.constant.entity",
@"meta.invalid",
@"markup.comment",
@"markup.inline.cdata",
@"markup.processing",
@"markup.tag.attribute.value",
@"markup.declaration",
		nil
	