//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



public class MsnbcItem : RssToolkit.RssElementBase {
    
    public MsnbcItem() {
    }
    
    public MsnbcItem(string title, string description, string link, string pubDate, string category, string guid) {
        base.SetAttributeValue("title", title);
        base.SetAttributeValue("description", description);
        base.SetAttributeValue("link", link);
        base.SetAttributeValue("pubDate", pubDate);
        base.SetAttributeValue("category", category);
        base.SetAttributeValue("guid", guid);
    }
    
    public string Title {
        get {
            return base.GetAttributeValue("title");
        }
        set {
            base.SetAttributeValue("title", value);
        }
    }
    
    public string Description {
        get {
            return base.GetAttributeValue("description");
        }
        set {
            base.SetAttributeValue("description", value);
        }
    }
    
    public string Link {
        get {
            return base.GetAttributeValue("link");
        }
        set {
            base.SetAttributeValue("link", value);
        }
    }
    
    public string PubDate {
        get {
            return base.GetAttributeValue("pubDate");
        }
        set {
            base.SetAttributeValue("pubDate", value);
        }
    }
    
    public string Category {
        get {
            return base.GetAttributeValue("category");
        }
        set {
            base.SetAttributeValue("category", value);
        }
    }
    
    public string Guid {
        get {
            return base.GetAttributeValue("guid");
        }
        set {
            base.SetAttributeValue("guid", value);
        }
    }
}

public class MsnbcImage : RssToolkit.RssElementBase {
    
    public string Url {
        get {
            return base.GetAttributeValue("url");
        }
        set {
            base.SetAttributeValue("url", value);
        }
    }
    
    public string Title {
        get {
            return base.GetAttributeValue("title");
        }
        set {
            base.SetAttributeValue("title", value);
        }
    }
    
    public string Link {
        get {
            return base.GetAttributeValue("link");
        }
        set {
            base.SetAttributeValue("link", value);
        }
    }
    
    public override void SetDefaults() {
        base.SetAttributeValue("url", "http://msnbcmedia.msn.com/i/msnbc/SiteManagement/SiteWide/Images/msnbc_logo.gif");
        base.SetAttributeValue("title", "MSNBC.com");
        base.SetAttributeValue("link", "http://www.msnbc.msn.com/");
    }
}

public class MsnbcChannel : RssToolkit.RssChannelBase<MsnbcItem, MsnbcImage> {
    
    public string Title {
        get {
            return base.GetAttributeValue("title");
        }
        set {
            base.SetAttributeValue("title", value);
        }
    }
    
    public string Link {
        get {
            return base.GetAttributeValue("link");
        }
        set {
            base.SetAttributeValue("link", value);
        }
    }
    
    public string Description {
        get {
            return base.GetAttributeValue("description");
        }
        set {
            base.SetAttributeValue("description", value);
        }
    }
    
    public string Copyright {
        get {
            return base.GetAttributeValue("copyright");
        }
        set {
            base.SetAttributeValue("copyright", value);
        }
    }
    
    public string Language {
        get {
            return base.GetAttributeValue("language");
        }
        set {
            base.SetAttributeValue("language", value);
        }
    }
    
    public string LastBuildDate {
        get {
            return base.GetAttributeValue("lastBuildDate");
        }
        set {
            base.SetAttributeValue("lastBuildDate", value);
        }
    }
    
    public string Category {
        get {
            return base.GetAttributeValue("category");
        }
        set {
            base.SetAttributeValue("category", value);
        }
    }
    
    public string Ttl {
        get {
            return base.GetAttributeValue("ttl");
        }
        set {
            base.SetAttributeValue("ttl", value);
        }
    }
    
    public MsnbcImage Image {
        get {
            return base.GetImage();
        }
    }
    
    public override void SetDefaults() {
        base.SetAttributeValue("title", "MSNBC.com: Top MSNBC Headlines");
        base.SetAttributeValue("link", "http://www.msnbc.msn.com/id/3032092/");
        base.SetAttributeValue("description", "MSNBC.com is a leader in breaking news and original journalism.");
        base.SetAttributeValue("copyright", "Copyright 2006 MSNBC.com");
        base.SetAttributeValue("language", "en-us");
        base.SetAttributeValue("lastBuildDate", "Sun, 26 Mar 2006 06:56:53 GMT");
        base.SetAttributeValue("category", "News");
        base.SetAttributeValue("ttl", "60");
        this.Image.SetDefaults();
    }
    
    public static MsnbcChannel LoadChannel() {
        MsnbcChannel channel;
        channel = new MsnbcChannel();
        channel.LoadFromUrl("http://rss.msnbc.msn.com/id/3032091/device/rss/rss.xml");
        return channel;
    }
    
    public static MsnbcChannel LoadChannel(string url) {
        MsnbcChannel channel;
        channel = new MsnbcChannel();
        channel.LoadFromUrl(url);
        return channel;
    }
    
    public static System.Collections.Generic.List<MsnbcItem> LoadChannelItems() {
        return LoadChannel().Items;
    }
}

public class MsnbcHttpHandlerBase : RssToolkit.RssHttpHandlerBase<MsnbcChannel, MsnbcItem, MsnbcImage> {
}
